### ISSUE TITLE
Pantheon admin bar ⚡️ style issue

### ISSUE THREAD

**Issue by westonruter** [pantheon-systems/WordPress#121]
I often notice that the Pantheon logo in the admin bar for the `wp-admin-bar-pantheon-hud` item will appear oversized momentarily until the footer scripts are loaded. On a page like the update screen where the footer output is delayed, the problem is exaggerated:

<img width="824" alt="screen shot 2017-06-08 at 10 43 12" src="https://user-images.githubusercontent.com/134745/26942640-a568f896-4c37-11e7-99d4-31ddc96cfcd8.png">

**Comment by danielbachhuber** [comment]
Thanks for the report, @westonruter. I've fixed this with https://github.com/pantheon-systems/pantheon-hud/pull/22
