### ISSUE TITLE
Remove Twenty Somethings

### ISSUE THREAD

**Issue by jhabdas** [pantheon-systems/WordPress#124]
It's unlikely anyone would ever need or want all of the WordPress Twenty* themes. In fact, I'd wager if you looked at your forks right now removing those is one of the first things everyone does (and I haven't even looked).

Please consider removing all but the latest Twenty Something themes from this base upstream.

**Comment by greg-1-anderson** [comment]
This could potentially cause conflicts &/or destruction for old sites that are using these old themes, so I think it is unlikely that we will do this clean-up.
