### ISSUE TITLE
Jetpack's Photon and locked sites

### ISSUE THREAD

**Issue by mboynes** [pantheon-systems/WordPress#13]
[Jetpack's Photon feature](http://jetpack.me/support/photon/) (free image CDN and dynamic image resizing tool) requires Automattic's ability to access images on a site. If I have a dev site password-protected (Environment access: locked), it can't access those images, and therefore Photon doesn't work. The way we've solved this problem when we run our own dev environments is to allow the Photon user agent (["Photon/1.0"](https://code.trac.wordpress.org/browser/photon/index.php#L602)) the ability to bypass http auth for the images directory.

I'm sure not everyone would want a back door to accessing images on a locked site, so I think the ideal solution would be for it to be optional. For instance, if there were an environmental variable one could set to enable it.

**Comment by tomharrigan** [comment]
+1

**Comment by amaschas** [comment]
+1

**Comment by joshkadis** [comment]
:100:

**Comment by zgreen** [comment]
+1

**Comment by dan-ai** [comment]
+1

**Comment by nstielau** [comment]
For clarification, are you referring to password-protecting the dev environment from Pantheon or within WordPress?

**Comment by mboynes** [comment]
I am referring to password-protecting the environment from within Pantheon, using the * Environment access: locked* feature.

**Comment by nstielau** [comment]
Ok, thanks.  That involves changes to our internal systems, nginx configs, etc.  I'll make an internal issue so we can evaluate this.

**Comment by mboynes** [comment]
Certainly, thanks!

**Comment by joshkoenig** [comment]
Hey all,

The challenge here is making this configurable, which is not a path that anything else goes down. How do people feel about making this a default for WP sites?

**Comment by mboynes** [comment]
I'm in favor of that being the default!

**Comment by kibra** [comment]
Hey all,

We've deployed an updated nginx.conf that will allow the Photon user agent to access files even on locked sites.

Sites should see this updated config within the next 3-4 days. If you'd like to get the updated config immediately, feel free to let me know and I can get you on the latest version.

-Kyle
