### ISSUE TITLE
References to deleted function

### ISSUE THREAD

**Issue by taupecat** [pantheon-systems/WordPress#132]
In two places in the Pantheon must-use plugin, you call a function (`_pantheon_disable_wp_updates`) that was removed in the last update.

Lines 71 & 75, using the `pre_site_transient_update_plugins` and `pre_site_transient_update_themes` filters, respectively.

Despite WP_DEBUG being turned off across all my Pantheon environments, PHP is throwing an error at this in the admin.

**Comment by greg-1-anderson** [comment]
#131

**Comment by aayler** [comment]
... and the PHP error in the admin breaks some functionality in the backend, for instance, the media library ...

**Comment by greg-1-anderson** [comment]
Deployed a fix.
