### ISSUE TITLE
Ignore differences to $wp_version revision number when wordpress-develop (src) is deployed

### ISSUE THREAD

**Issue by westonruter** [pantheon-systems/WordPress#135]
I have an environment where I have `SCRIPT_DEBUG` enabled and am pushing out the files directly from wordpress-develop where the `$wp_version` is `4.9-alpha-40870-src`. Even though I have the latest from `trunk`, in the dashboard I see this message:

![image](https://user-images.githubusercontent.com/134745/30825168-e2998bcc-a1e6-11e7-9d11-7df4502bc95d.png)

I think it is because the nightly build bumps the changeset rev number in `$wp_version` whereas each commit to `wordpress-develop` does not (it only gets bumped with each beta/rc/final).

So I think that if `-src` appears in `$wp_version` that the revision number should be ignored from consideration when determining if there are new changes to update to.

**Comment by ataylorme** [comment]
@westonruter can you test #136?

**Comment by westonruter** [comment]
@ataylorme tested, feedback provided.
