### ISSUE TITLE
Add RETURN_TO_PANTHEON_BUTTON check

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/WordPress#153]
Some folks want to disable the return to Pantheon button. It is not trivial to do so. We should check for a `RETURN_TO_PANTHEON_BUTTON` constant and, if it is false, skip adding the button to begin with.

The constant can then easily be defined in `wp-config.php`

**Comment by greg-1-anderson** [comment]
The use-case that this feature was designed to address was new users creating a new WordPress site on Pantheon, and being confused, upon reaching the WordPress login page, on how to return to the Pantheon dashboard.

The return to pantheon button is not useful to the end users of a site, though (anyone who does not have a login on the Pantheon dashboard that has access to that site). Perhaps it would still meet the original use-case if the return-to-pantheon button was automatically hidden in the TEST and LIVE environments.

Having a constant to also disable it in dev / multidev environments also sounds like a good idea.

@kimby77 ^^

**Comment by stevector** [comment]
+1 for "automatically hidden in the TEST and LIVE environments." The switch could also happen based on whether the current domain contains `pantheonsite.io`

**Comment by kimby77** [comment]
Yes, this is intended for new users to improve Pantheon's first time user experience and provide that connection from their site back to Pantheon.  I believe that objective would be met if at a minimum it showed up on Dev.  I agree this wouldn't be useful for users who only need to log in to the Live site.

So please keep this on Dev, I have no strong opinion whether this should be on Test, and it's ok to remove from Live.

**Comment by greg-1-anderson** [comment]
Test should always behave the same as the live site (or as close as possible), IMO

**Comment by ataylorme** [comment]
Here is my current plan:

1) Add a `RETURN_TO_PANTHEON_BUTTON` constant as described above to allow for disabling the button
1) Check `$_ENV['PANTHEON_ENVIRONMENT']` and disable the button if on `test` or `live` and the constant above is not defined

@kimby77 and @greg-1-anderson does this work for you? Also, will we want to roll out this update as its own release before the next version of WordPress?

**Comment by kimby77** [comment]
That's good with me @ataylorme

**Comment by greg-1-anderson** [comment]
Works for me. Timing of release is up to product. @ari-gold @joshkoenig

**Comment by greg-1-anderson** [comment]
@stevector's suggestion also has merit (auto-disable for vanity domains)

**Comment by tinefin** [comment]
One more customer report of this, mentioning:

> Its a security policy for us not to expose the origin.

I'm not sure hiding origin is possible, but I do see the point in not shouting it out.

**Comment by ataylorme** [comment]
@ari-gold 

> Done When
> - See "Return to Pantheon" button when viewing WP login form via platform domain on any environment (Dev, Test, Live, N-Multidev)
> - Do not see"Return to Pantheon" button when viewing WP login form via a custom or vanity domain on any environment

This sounds good to me. Let me know if I should proceed with making that change to the PR

**Comment by ari-gold** [comment]
Please proceed. Thanks @ataylorme !

**Comment by ataylorme** [comment]
Closed by #156
