### ISSUE TITLE
Issue with Auto Update

### ISSUE THREAD

**Issue by mhigbee** [pantheon-systems/WordPress#173]
I updated our code base on dev with one click updates and the pantheon updates file was (https://github.com/pantheon-systems/WordPress/blob/master/wp-content/mu-plugins/pantheon/pantheon-updates.php) missing some lines of code when this happened. It made the site not launch and I had to manually import the raw code locally and push to dev.

Your support asked that I include this ticket to hopefully resolve in the future.

**Comment by greg-1-anderson** [comment]
It would actually be better if support could provide the support ticket to engineering. Without a reference to your site, it would be hard to know what happened here.

**Comment by CdrMarks** [comment]
Hi @mhigbee, I'm following up on this old issue to see if you saw Greg's comment.  I'm going to leave this open for a week and will close this if we don't hear back from you.
