### ISSUE TITLE
Update to 4.9.9

### ISSUE THREAD

**Issue by brettgoldhammer** [pantheon-systems/WordPress#185]
@greg-1-anderson   

Would it be possible for Pantheon to update the 4.9.8 branch with the 4.9.9 security release to accomodate users on Custom Upstreams, not yet ready to move to 5.0?

If not can you outline any things to watch out for if this is attempted manually.

Thanks!

**Comment by greg-1-anderson** [comment]
@brettgoldhammer The 4.9.9 tag is now available. Please see the [advisory in the pull request](https://github.com/pantheon-systems/WordPress/pull/186), as using the 4.9.9 tag is **not** recommended in almost all cases.

**Comment by brettgoldhammer** [comment]
Thank you Greg, this is exactly what we were looking for.
