### ISSUE TITLE
Custom Login Screen should use customized login_message

### ISSUE THREAD

**Issue by wonkeythemonkey** [pantheon-systems/WordPress#192]
Wordpress allows you to modify the message displayed on the login screen using the `login_message` action, like so:
```php
add_filter('login_message', function () {
    return 'Login below for awesomeness!';
});
```

However, the default Wordpress login message is hard-coded into Pantheon's customizations:

https://github.com/pantheon-systems/WordPress/blob/84f059b2b4ca68ca4fa1d33dafa4eb979a542d23/wp-content/mu-plugins/pantheon/pantheon-login-form-mods.php#L60-L62

The resulting output is the custom login message above the login container and the default message inside it (see screenshot):

![Log_In_Screen_Demo](https://user-images.githubusercontent.com/4974766/54289829-3b07ad00-4580-11e9-82fa-b8438d9c893a.png)

Is it possible for Pantheon to use the customized message in place of the default message, if it exists?

Wordpress gets the custom login message using the following code:
```php
$message = apply_filters( 'login_message', $message );
if ( ! empty( $message ) ) {
    echo $message . "\n";
}
```
https://github.com/WordPress/WordPress/blob/c78d28d9f10bf9de2c2c08d0c9b529e237b6836b/wp-login.php#L202-L205

**Comment by ataylorme** [comment]
Hi @wonkeythemonkey,
That seems like a reasonable request. Would you like to submit a pull request?

**Comment by wonkeythemonkey** [comment]
If I can find the time in the near future, I'd love to. It will probably take a bit of time to stand up a testing environment to confirm my code works.

Do you have a contributor guide? How do you perform testing?

**Comment by ataylorme** [comment]
> It will probably take a bit of time to stand up a testing environment to confirm my code works.

@wonkeythemonkey I can take care of testing if you just want to submit a PR with the code. I mostly want to make sure your name is on the PR so you get credit 😄 

If you would like to test as well the easiest way to do that would be on a Pantheon site. If you have an existing one, a [multidev environment](https://pantheon.io/docs/multidev) would work nicely. You can set it SFTP mode and make edits directly.

When the code is in a state that you like it then you can open the PR to this repository.

Once the PR is merged the change will go out to Pantheon with the next WordPress release.
