### ISSUE TITLE
wp-config-pantheon.php says not to edit and to edit

### ISSUE THREAD

**Issue by EdwardAngert** [pantheon-systems/WordPress#252]
`wp-config-pantheon.php` starts out by saying ([L6](https://github.com/pantheon-systems/WordPress/blob/default/wp-config-pantheon.php#L6)):
> Do not modify this file. This file is maintained by Pantheon.

Then in the hashing section, [L35](https://github.com/pantheon-systems/WordPress/blob/a9d9c261c1565670afd6a5357536c179c0b4c43e/wp-config-pantheon.php#L35) says:
> Change these to different unique phrases!

We can add information to the [documentation](https://pantheon.io/docs/migrate-manual)(update in progress to include this file) about whether and how to modify this section, and I wanted to check with you all about it first.

**Comment by pwtyler** [comment]
The comment section there is from the default WordPress `wp-config.php` ([here](https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php#L40-L-48)), but unlike a "normal" wp-config (which isn't usually in version control), Pantheon sets those values using environment variables. We should update the comment here in wp-config-pantheon.php to just [L39-40](https://github.com/pantheon-systems/WordPress/blob/a9d9c261c1565670afd6a5357536c179c0b4c43e/wp-config-pantheon.php#L39-L40).
