### ISSUE TITLE
Can we use hyperdb or some other mechanism to scale read queries?

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#26]
Investigation into using our MariaDB replica capabilities along with the hyperdb plugin (or another mechanism) to scale out read-only queries.

Some real-world use-cases:

- A site with a large amount of posts may have some slow queries when generating various listings. At scale, the ability to run these against a replica DB will improve site performance and stability by preventing the master DB from being overloaded.
- If there's "heavy" reporting component to a site — e.g. a custom admin area or the like — generating this off the replica database is good as it prevents this from impacting the "front end" user experience.
- Sites with heaps and heaps of traffic can saturate the network interface to a single database back-end. Being able to spread the load is the only way to overcome the ultimate NIC bottleneck.

The PHP environment configuration will have the following variables available when a replica is present:

```
REPLICA_DB_HOST=xxx.xxx.xxx.xxx
REPLICA_DB_PORT=xxxx
REPLICA_DB_USER=xxxx
REPLICA_DB_PASSWORD=xxxx
REPLICA_DB_NAME=xxx
```

**Comment by danielbachhuber** [comment]
@joshkoenig could you update the description with an example of a real world use case?

**Comment by danielbachhuber** [comment]
Did a bit of technical discovery on this today, which included setting up HyperDB on a production Pantheon instance:

* The good news: it was really easy to do. Dangerously easy. Plus, HyperDB functions as a drop-in replacement for WPDB even when you don't have replicas.
* The bad news: HyperDB is a super user tool, with tons of tuning options based on database architecture and network topology.

For the purposes of this issue, my recommendation would be to produce a few stock configurations users and/or support can reference as they configure HyperDB for a high-traffic site. These configurations would be:

1. Split reads between master and replica, for those who have high load they want to split between two databases.
2. Admin reads and writes to master, and replica serves frontend reads, for those who want to better ensure dashboard availability during high frontend load.
3. Shard reads based on blog ID, for those running multisite.

I prefer documentation as close to the code as possible, so my recommendation would be to include HyperDB in this WordPress repo disabled, and then I can commit the configurations alongside.

As a super awesome bonus, it would be great if we could expose DB load to users and/or support in some simple way, so they have easy access to the before and after impact of using HyperDB.

**Comment by danielbachhuber** [comment]
Assigning to @joshkoenig to land the documentation I wrote.

**Comment by joshkoenig** [comment]
Solid. We got the docs.

**Comment by 7php** [comment]
Hey @danielbachhuber I have some questions, grateful if you can help:
1) what tools do you use to "expose DB load to users" to see metrics of "the before and after impact of using HyperDB" ? (or can recommend to use for my perusal)
2) HyperDB looks outdated on the WP repo, is it still good to use with the latest version of wordpress (v3.5.2 at the moment)

@joshkoenig is [this the docs](https://pantheon.io/docs/hyperdb/) being referred or is another doc? Would like to go through for my knowledge in the matter

I thank you both for your time.
