### ISSUE TITLE
Admin notices query on every admin-ajax.php request

### ISSUE THREAD

**Issue by tripflex** [pantheon-systems/WordPress#262]
After digging through New Relic I found a ton of calls to check for updates:

![image](https://user-images.githubusercontent.com/553732/95893322-ceedbc00-0d55-11eb-9bda-3a145067a4c3.png)

Tracked this down to the fact that our site heavily relies on `admin-ajax.php` on the frontend to do majority of lifting, causing the update check to run every time an ajax request is made.

https://github.com/pantheon-systems/WordPress/blob/ba8b498ea60204c07dd27fb22673c26f53c24aa5/wp-content/mu-plugins/pantheon/pantheon-updates.php#L118-L126

There's no reason this request should be made/checked when ajax is being ran, so check should be added to only run when not doing ajax request.

Because `wp_doing_ajax()` is loaded in `load.php` which is included before any mu plugins are ran, it should be fine to check if doing ajax before making the query.

Sort-of similar to #174 (which would be just completely disabling it), i'll submit a PR for this.

**Comment by nullvariable** [comment]
hi @tripflex this api request should be cached for 2 minutes, so you should only be seeing one request every 2 minutes unless something different is going on with your transients. I think #174, or the ability to set the timeout before rechecking would probably make the most sense here.

see: https://github.com/pantheon-systems/WordPress/blob/d52cebde1c7369c8ee017bb75c0ea7792f1f2cf8/wp-content/mu-plugins/pantheon/pantheon-updates.php#L85-L95

**Comment by tripflex** [comment]
@nullvariable I respectfully disagree.

Yes I saw the value is cached, but regardless there's zero reason for this to be running during AJAX requests.

If the rational would be to have that value cached already, no site administrator would agree that they would prefer the extra load time to be attributed to frontend users, rather than the admin user actually accessing the admin area.

**_Since all this does is show an update nag_**, this should only be ran when the admin area is actually accessed, not run every single time an AJAX request is made (even if the value is cached).

**Comment by nullvariable** [comment]
that's fair, I don't have an objection to that, just wanted to ensure that we're not adding things that aren't needed. I think since the ajax api is accessed via admin even for non-admin calls that your logic is sound. I'm also going to open a PR for #174 as an alternative
