### ISSUE TITLE
WP-CLI interface for cache clearing

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#27]
The interface for "clear all" works fine, but we should also have a CLI interface to purge individual urls. 

This is definitely similar to #28, but I believe we should be able to define the interface for this even if it uses the old BAN method internally.

I would imagine the steps to be something like:

1. Distinguish the code paths for "clear all" and "clear this array of paths" in `pantheon-cache.php`
2. Make sure that the general cache clear command uses clear all, and that there's a dedicated CLI for clearing a specific set of up to 10 paths.
3. Make sure that the specific path-clearing operation uses the preferable PURGE api instead of the old BAN api.

**Comment by danielbachhuber** [comment]
@joshkoenig Close if you're happy with this?

**Comment by joshkoenig** [comment]
Yah sorry. Used to the PR doing it automagically for me. ;)
