### ISSUE TITLE
Use with Kubernetes?

### ISSUE THREAD

**Issue by balibebas** [pantheon-systems/WordPress#271]
How well does this template perform on Kubernetes?

**Comment by balibebas** [comment]
Nevermind I figured it out. https://habd.as/post/move-pantheon-wordpress-site-kubernetes/

**Comment by nullvariable** [comment]
this is spam @greg-1-anderson or @pwtyler and should be deleted

**Comment by balibebas** [comment]
@nullvariable is it spam because it's unrelated to this project, or spam because it cuts into the Pantheon bottom line? because if it's the former I think I could argue it's not at all spam—it's called open core. 😄

**Comment by greg-1-anderson** [comment]
I do not believe that this is spam. It is a feature of Pantheon that you can take your Pantheon-hosted sites and move them to some other platform at any time if you no longer want to stay with Pantheon.

Regarding cutting into the bottom line, it is my opinion that Pantheon offers an amazing unbeatable value for sites whose traffic fits into the basic plan tier, and I also think that we are very well suited to serving our largest customers, whom I think would be hard pressed to hire internal staff more economically than their contract price and still get equivalent performance and service. However, for sites that just exceed the limits of the basic plan, I agree with the blog author that there is a gap in our offerings, and prices rise too quickly for mid-tier sites that do not have the needs of a large enterprise site, but don't fit into the basic plan any more either. Other customers have made similar observations. I am in engineering, though, not marketing, so I have no insight into whether there is any interest in addressing this segment in the future.

**Comment by joshkoenig** [comment]
I leave it to the reader to evaluate the intent of an issue that is opened and immediately closed with a link to OPs blog. 

To Greg's point about the gap between the tried and true "basic" plan and our Performance offerings, it's material, especially the way traffic volume is allocated. I've heard that feedback quite a bit, especially as we've started enforcing our limits on a more regular basis.

However, this is something we'll likely address in a more wholesale refactor of how we price/package, which is just in the early stages of planning. While there could be an interum step of a "basic plus" plan, that's not currently on the roadmap. I wouldn't expect a change here until sometime in 2022 when we're ready to change things up in ways that are likely to de-emphasize the role of traffic in our pricing.

The honest truth is we're not a great value if:

1. you have the technical wherewithal to time to set up and your own Kube cluster
2. you also have the time for said setup, and ongoing operations

Our price is based on the value of relieving the client from having to do that initial build and any ongoing maintenance. If that's "free" to you, then you may be better off with a DIY approach.
