### ISSUE TITLE
Update-nag formatting has gone missing

### ISSUE THREAD

**Issue by joe-westcott** [pantheon-systems/WordPress#274]
At some point a few months back, some of the formatting of the .update-nag was lost.

The nag used to have formatting that looked something like this:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/13838392/108781178-7ca87d00-7537-11eb-8fbd-4998a40ca346.png">

And now it's missing some of the formatting that makes the notice stand out. The nag now looks like this instead:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/13838392/108780242-1e2ecf00-7536-11eb-821c-1dfa3779da31.png">

If you'd agree that this nag should be formatted like other notices, then the solution might be to update this file:
wp-content/mu-plugins/pantheon/pantheon-updates.php

Where this code appears:
`<div class="update-nag">`

And update that line to include classes that apply Wordpress "notice" styling to that div, like so:
`<div class="update-nag notice notice-warning">`

Would that be okay?

**Comment by CdrMarks** [comment]
Hi @joe-westcott, I'm unsure if you saw that Greg gave a :+1: on your comment.  Are you able to provide a pull request for this change?

**Comment by joe-westcott** [comment]
Thanks for flagging, @CdrMarks. I didn't get a notification for the thumbs-up, so I appreciate that you let me know.

Yes, I can and will provide a pull request for this. I'll close this issue when I submit the pull request, unless you'd like me to close this issue right away.

**Comment by CdrMarks** [comment]
@joe-westcott You can leave this one open for now.  When you submit the PR, please use Fixes #___ so that when the PR is merged, this issue will be closed.
