### ISSUE TITLE
Use PURGE api rather than BAN for page-specific cache clearing (placeholder)

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#28]
If we switch to the PURGE api it will scale much better. 

There are two methods for clearing items from Pantheon's edge cache: BAN and PURGE. The original BAN method is required to clear the cache site-wide (it can blacklist an entire domain name), but the PURGE method scales much better for clearing specific urls. It's the preferred method for a "pinpoint" cache-clear.

Currently the code only makes use of `pantheon_clear_edge()` which is an internal function that uses the BAN method to clear cached pages. It also does the courtesy of doing the cache clearing as a shutdown function.

There is a more powerful internal function called `pantheon_purge_edge_urls()` which supports passing an array of up to 10 paths to the PURGE api. However it is currently also a bit more low-level: it has a complex function signature and doesn't do shutdown-function niceness. 

We want to distinguish our cache-clear paths from the "clear all" use-case, which should continue calling `pantheon_clear_edge()` (with no args), and the case where a specific path or up to 10 paths are meant to be cleared out.

We also need to determine whether we should implement the pantheon_purge_edge_urls() function directly, or spec a better interface.

**Comment by danielbachhuber** [comment]
@joshkoenig Are you open to sharing the internals of these functions publicly, so I can more easily mock them in a non-Pantheon environment? Or what's a better way for me to understand how `pantheon_purge_edge_urls()` works?

**Comment by joshkoenig** [comment]
I can definitely share the function signature, but mocking it will be kind of tough.

**Comment by stevector** [comment]
I think with [Pantheon Advanced Page Cache](https://wordpress.org/plugins/pantheon-advanced-page-cache/ ) released we can close this issue. That plugin pairs with major improvements to cache handling.
