### ISSUE TITLE
Invalid WP_TEMP_DIR value causes file upload issues.

### ISSUE THREAD

**Issue by ivanbueno-jcc** [pantheon-systems/WordPress#282]
The value of WP_TEMP_DIR is "//tmp" in:
https://github.com/pantheon-systems/WordPress/blob/94ce7019e7a07cbcd0ab924da53254252a14d217/wp-config-pantheon.php#L68

$_SERVER['HOME'] returns '/'.

This causes upload issues for plugins like Drag and Drop Multiple File Upload, Contact Form 7 upload, etc.

On the server, you'll get errors like this:
`2021/07/26 21:47:33 [crit] 9#0: *76 mkdir() "/tmp/nginx/7" failed (2: No such file or directory), client: 10.1.3.92, server: , request: "POST /wp-admin/admin-ajax.php `

To fix, I updated the line to:
`define('WP_TEMP_DIR', '/tmp');`

**Comment by greg-1-anderson** [comment]
Perhaps `define('WP_TEMP_DIR', sys_get_temp_dir());` would also be a valid fix?

**Comment by ivanbueno-jcc** [comment]
> Perhaps `define('WP_TEMP_DIR', sys_get_temp_dir());` would also be a valid fix?

Yes, it works. That's a better fix.
