### ISSUE TITLE
SimpleSAMLphp support

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#29]
We currently offer support for SimpleSAMLphp on the platform:

https://pantheon.io/docs/articles/drupal/using-simplesamlphp-with-shibboleth-sso/

But there is not a good WordPress plugin that "just works" with this. Should we create one?

**Comment by mattpaz** [comment]
At one point in time, I helped upgrade the D7 module.  
If I get time, I might be interested in helping out with this.

**Comment by joshkoenig** [comment]
We're going to do this as a separate project.
