### ISSUE TITLE
Make this be require-able via Composer for portability

### ISSUE THREAD

**Issue by bradymwilliams** [pantheon-systems/WordPress#291]
Example: https://github.com/johnpbloch/wordpress
Which installs https://github.com/johnpbloch/wordpress-core

and is requirable in composer like

"johnpbloch/wordpress": "x.x.x",

**Comment by greg-1-anderson** [comment]
See https://github.com/pantheon-systems/wordpress-composer and https://github.com/pantheon-upstreams/wordpress-project.

We'll be coming out with a supported version based on Bedrock in the future.

**Comment by scottbuscemi** [comment]
We are now in EA for the WordPress Bedrock Composer upstream: https://github.com/pantheon-systems/wordpress-composer-managed

If you'd like to participate in the EA program, please fill out this form: https://docs.google.com/forms/d/e/1FAIpQLSe5WvxnzA7_U7B4clhhIYsPxI7DXkmQC-Y8J6pXmrbHYPzviw/viewform
