### ISSUE TITLE
6.0.5 Security Patch

### ISSUE THREAD

**Issue by brettgoldhammer** [pantheon-systems/WordPress#364]
Hello,

We are currently running on an older version of Wordpress. I know that there are typically tags for older core updates ([like this one for 6.0.4 I used last week](https://github.com/pantheon-systems/WordPress/releases/tag/6.0.4)). Would it be possible to tag a 6.0.5 branch from the latest release over the weekend?

Thanks!
Brett

**Comment by jspellman814** [comment]
Thanks for this report, Brett. Looks like there is an issue with our automation that pushes updated tags. We will take a look at this, and I have created a ticket (BUGS-6290) to track internally.

**Comment by pwtyler** [comment]
Hey @brettgoldhammer, I've just confirmed the tag automation is fixed and [6.0.5](https://github.com/pantheon-systems/WordPress/releases/tag/6.0.5) just pushed a minute ago.
