### ISSUE TITLE
Integration test suite

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/WordPress#40]
We should have an integration test suite in this repo, to smoke test the WordPress installation and to ensure the Pantheon-specific functionality works as expected.

**Comment by jhabdas** [comment]
@danielbachhuber Do you have a set of smoke tests and a CI rig configured for this? I don't feel this repo is the appropriate place for a test scaffold.

**Comment by stevector** [comment]
I think we can close this issue. This repo does have CircleCI tests configured through the Circle UI so that no testing files are added to the repo.
