### ISSUE TITLE
Akismet and merge conflicts

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/WordPress#51]
The majority of Upstream update failures occur as a result of users who delete the Akismet plugin from their site repository. Every time this happens before an Akismet update, and we update the plugin in the upstream repo to match, these users end up having to reinstall Akismet to resolve their conflicts with the upstream. https://github.com/wordpress/wordpress does not have Akismet bundled.

Options, I think:

1. Stop updating Akismet here.
2. Delete akismet from the upstream. This would require a check for the presence of the plugin in dev environment repos, and then a prompt for users to reinstall the plugin before deploying out to Test and Live.

**Comment by joshkoenig** [comment]
We have changed our process to stop pulling in plugin or theme updates from the github upstream. This should minimize conflicts going forward.
