### ISSUE TITLE
Support Only Core Updates

### ISSUE THREAD

**Issue by craychee** [pantheon-systems/WordPress#53]
A review of automated upstream updates indicates a high failure rate around Wordpress users applying updates that include plugins (such as Akismet) and themes.

It has been agreed by a quorum of stakeholders that moving forward, Pantheon will only support Core updates.

Additional tasks: Update documentation (cc/ @bmackinney).
Related: https://github.com/pantheon-systems/WordPress/issues/51

**Comment by ttrowell** [comment]
@craychee @greg-1-anderson Will Akismet and old themes be .gitignored when this task is completed?
I just wanted to clarify how sites would avoid conflicts while the files are still in our codebase, yet not updated.

Thanks!

**Comment by greg-1-anderson** [comment]
Good question.

Our current policy is to keep Akismet and the WP themes in the repository, and not .gitignore them. The odd thing about this is, if someone installs a new WP site on Pantheon, their Akismet and themes will be old; they will need to update them manually if they plan on using them.

For everyone else, it will also be necessary to manually update any of these components that are in use. Whether the site is new or old, the update can be done easily on the WP admin pages. Even though these files also exist in the Pantheon upstream repository, committing them in a user site will not cause conflicts, as we are never going to commit changes to these components again. No changes in the upstream == no conflicts.

@bmackinney: is there a documentation PR for this? I'd be happy to review it if so.

**Comment by bmackinney** [comment]
@greg-1-anderson https://github.com/pantheon-systems/documentation/pull/1321.

**Comment by ari-gold** [comment]
Why not just remove the themes/Akismet plugin from this repo as part of the next WordPress release? And include release notes in that update that people can add those plugins and themes back in if they'd like, with the understanding that it is their responsibility to keep them up to date. Having outdated themes/plugins in our upstream that could eventually be insecure seems like something we'd want to avoid.

**Comment by greg-1-anderson** [comment]
I don't think the auto-update feature on the admin dash would work right for new installs if there was nothing in the repo.  Also, I think that once a file is in the repo, we can't take it out without causing conflicts for everyone using it -- or worse, cause the files to disappear from their repo also, as git will see the removal and enforce the deletion on all of the downstream repos.

**Comment by bmackinney** [comment]
I agree that it will cause the files to disappear, and that's what @ari-gold is saying we could communicate very clearly: "if you want to keep using twenty-sixteen or whichever you're using, you need to reinstall it in a CDE before deploying to Test and Live". I think that option would take an email blast to WordPress site owners and team members coinciding with that core update, and would likely add a couple of steps to the upstream update process, to keep those files out of the repository. (Themes are present in the upstream's upstream at https://github.com/WordPress/WordPress/tree/master/wp-content, Akismet is not)

**Comment by craychee** [comment]
@bmackinney and @greg-1-anderson and @ari-gold we are not removing anything, we are no longer updating Akismet and other non-core WP. We are doing now only doing in-place WP core updates.
