### ISSUE TITLE
wp cli & pantheon wordpress

### ISSUE THREAD

**Issue by danyalette** [pantheon-systems/WordPress#59]
as per [this wp-cli issue](https://github.com/wp-cli/wp-cli/issues/1631) and [its fix](https://github.com/wp-cli/wp-cli/issues/1631#issuecomment-173314103): is there a particular reason that `require_once(ABSPATH . 'wp-settings.php');` is both in `wp-config.php` _and_ in `wp-config-local.php`/`wp-config-sample.php`? In `wp-config.php`, the require occurs after the end of the `if` block; so, presumably, the require in `wp-config.php` gets evaluated regardless of whether the site is being run locally or in the Pantheon environment.

**Comment by jhabdas** [comment]
@danyalette is there anything actionable here? or a question, perhaps? if not, would you kindly close this issue to help keep the repo clean for others?

**Comment by dylanjameswagner** [comment]
@danyalette In a default WordPress install there is no `wp-config.php` but there is a `wp-config-sample.php` from which to create a `wp-config.php`. Pantheon goes a step further in the installation process and provides a preconfigured custom `wp-config.php` for us.

There is no provided `wp-config-local.php` in a Pantheon install, if you have one of those it has been created by someone on your team, possibly copied from the `wp-config-sample.php` which is not  the best reference for this usage. Instead, I have always referenced what is inside the `if (file_exists(dirname(__FILE__) . '/wp-config-local.php') ... else ...`

I have gotten into the habit of creating a `wp-config-local.php` and a `wp-config-local-sample.php` (the latter of which will be tracked) for future team members reference. Which usually looks like this: 

```
<?php
define('DB_NAME',     'database_name_here');
define('DB_USER',     'username_here');
define('DB_PASSWORD', 'password_here');
define('DB_HOST',     'localhost');
define('DB_CHARSET',  'utf8');
define('DB_COLLATE',  '');

define('AUTH_KEY',         'put your unique phrase here');
define('SECURE_AUTH_KEY',  'put your unique phrase here');
define('LOGGED_IN_KEY',    'put your unique phrase here');
define('NONCE_KEY',        'put your unique phrase here');
define('AUTH_SALT',        'put your unique phrase here');
define('SECURE_AUTH_SALT', 'put your unique phrase here');
define('LOGGED_IN_SALT',   'put your unique phrase here');
define('NONCE_SALT',       'put your unique phrase here');

define('WP_DEBUG',         true);
define('WP_DEBUG_LOG',     true);
define('WP_DEBUG_DISPLAY', true);

define('WP_AUTO_UPDATE_CORE', false);

define('WP_HOME',    'http://' . $_SERVER['HTTP_HOST']);
define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
```

I totally understand how compiling this could be confusing/complicated. I may submit a new issue requesting the addition of a `wp-config-local-sample.php` to help others find the way.
