### ISSUE TITLE
WP 4.3.2 update

### ISSUE THREAD

**Issue by brettgoldhammer** [pantheon-systems/WordPress#61]
We are running a custom upstream that, due to various reasons, is currently a version behind the latest Wordpress version. I am in need of a way to pull update from this repo to update v4.3.1 to v4.3.2. 

Would it be possible to apply a v4.3.2 update to the v4.3.1 branch. It seems as though this could be a need every time a security patch is released on a version of wordpress that is not the latest available.

**Comment by ttrowell** [comment]
The recommended course of action is to update directly from Wordpress for this version and all necessary patches  - should they be created:

https://github.com/wordpress/wordpress

At the point that the latest version of WP core can be used in the custom upstream, switch back to merging from the Pantheon upstream.  There may be conflicts that need to be resolved, but those should be able to be worked out fairly easily.
