### ISSUE TITLE
All /icons/ Directory in files ignored.

### ISSUE THREAD

**Issue by scottbasgaard** [pantheon-systems/WordPress#66]
https://github.com/pantheon-systems/WordPress/blob/master/.gitignore#L45

This is pretty generic and ignored something like:
`/wp-content/plugins/plugin-name/css/icons`

**Comment by scottbasgaard** [comment]
For now I'm just doing:

`!icons/

**Comment by paulgibbs** [comment]
Yes, can we get this ignore modified to be more precisely targeted, or removed all together? This has bit me on several projects.

**Comment by MikeNGarrett** [comment]
Currently discussing in #76. I'd love to get your thoughts.

**Comment by dylanjameswagner** [comment]
The issue discussed in #76 has been merged. I think this issue can be closed.
