### ISSUE TITLE
Clarify developer interface for cache clearing

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#68]
Sometimes developers need to clear caches programatically. Currently this is way too unclear.

It's a more general question that also applied to Drupal projects, but it came up recently on Power Users list related to WordPress. 

Perhaps we need to provide a clean/safe wrapper around `pantheon_clear_edge()` that won't die if we are off-platform. Also, we should likely insure this is using the PURGE method under the hood, as opposed to BAN.

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/pantheon-systems/pantheon-integrated-cdn/issues/16
