### ISSUE TITLE
WP_MAX_MEMORY_LIMIT set to 256MB

### ISSUE THREAD

**Issue by hengkit** [pantheon-systems/WordPress#78]
The maximum memory limit is set to 256 MB by default. This would not affect self-service plans but business and elite plans have 512MB allocated. 

https://github.com/pantheon-systems/WordPress/blob/master/wp-includes/default-constants.php#L30

**Comment by dustinleblanc** [comment]
Perhaps this can be injected via the environment?
```
define('WP_MAX_MEMORY_LIMIT, $_ENV['PHP_MEMORY_LIMIT'])
```
or something like that?

**Comment by danielbachhuber** [comment]
A somewhat related core ticket: https://core.trac.wordpress.org/ticket/32075

> The maximum memory limit is set to 256 MB by default. This would not affect self-service plans but business and elite plans have 512MB allocated.

Can you share the public-safe background to this request? I don't think you necessary want _every_ request taking 512 MB, so I'm not quite sure whether it makes sense to set it as a high value by default.

**Comment by hengkit** [comment]
I only noticed it when looking at a bbPress OOM error on an elite site. I don't think a higher limit is strictly necessary for most use cases but could it possibly help for WP multisite performance or other edge cases? I don't have a strong case for changing it but I did want to note it.

**Comment by danielbachhuber** [comment]
> I don't think a higher limit is strictly necessary for most use cases but could it possibly help for WP multisite performance or other edge cases?

WordPress itself (including multisite) should run fine on 256 MB max memory. However, throw any plugins into the mix and you can easily run into memory issues.

> I only noticed it when looking at a bbPress OOM error on an elite site.

It'd be worthwhile to see if this issue has already been reported to bbPress, to see if it can be fixed in a future release.

**Comment by JJJ** [comment]
Howdy! bbPress lead chiming in. @hengkit, are you able to provide any additional context into when the OOM condition occurs?

Several significant query improvements are in bbPress 2.6 that could directly impact this, but without knowing exactly, it's hard to know for sure.

Now that I'm subbed here, I'll reply if any new details come in.

**Comment by nullvariable** [comment]
This issue appears to have been resolved in the core upstream, defaulting to 256MB unless a higher value is found. I am seeing the correct default values for platform sites based on plan.

I believe we can close this issue cc @greg-1-anderson

**Comment by pwtyler** [comment]
Thanks @nullvariable.
