### ISSUE TITLE
Update the Pantheon Cache must use plugin to use new cache API's

### ISSUE THREAD

**Issue by kibra** [pantheon-systems/WordPress#84]
Maintain current functionality of, using new Pantheon API's:
- Default Cache Time setting
- Clear Site cache button should use `pantheon_clear_edge_all`

Remove selective cache clearing functionality:
- clean_post_cache
- clean_term_cache
- admin_post_pantheon_cache_delete_page
- pantheon-cache-cli.php

A new contrib plugin will provide new and improved selective cache clearing functionality.

**Comment by danielbachhuber** [comment]
@ari-gold Do you know whether the new `pantheon_clear_edge_paths()` is functionally equivalent to `pantheon_clear_edge()`, or will I need to make some modifications?

**Comment by danielbachhuber** [comment]
@kibra Do `admin_post_pantheon_cache_delete_page` and `pantheon-cache-cli.php` need to be replicated in Pantheon Integrated CDN?

**Comment by kibra** [comment]
@danielbachhuber Re. your first question, I don't think we should need to use `pantheon_clear_edge_paths` here. Where the plugin uses `pantheon_clear_edge`, we should be able to replace it with `pantheon_clear_edge_all`

Re. your second question, I do think we want to replicate `pantheon-cache-cli.php` functionality in the new plugin, I forgot to bring that up. I'll double check.

What exactly is the functionality of `admin_post_pantheon_cache_delete_page`? My understanding was the new plugin will provide that same functionality implicitly.

**Comment by danielbachhuber** [comment]
> Re. your second question, I do think we want to replicate `pantheon-cache-cli.php` functionality in the new plugin, I forgot to bring that up. I'll double check.

Ok.

> What exactly is the functionality of `admin_post_pantheon_cache_delete_page`? My understanding was the new plugin will provide that same functionality implicitly.

To clear a specific URI, hence the use of `pantheon_clear_edge_paths()`:

![image](https://cloud.githubusercontent.com/assets/36432/19952115/07c07f00-a120-11e6-899c-aa69513e78fe.png)

Are we:

1. Leaving this functionality as-is in the upstream?
1. Moving the functionality to the plugin?
1. Removing the functionality entirely?

**Comment by danielbachhuber** [comment]
@kibra Any updates on the two remaining questions?

**Comment by ari-gold** [comment]
Created https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/48 and https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/49 to move WP-CLI and admin_post_pantheon_cache_delete_page functionality to the new plugin.

**Comment by ari-gold** [comment]
@danielbachhuber  As part of this work, we'd like to rename this must use plugin to  "Pantheon Page Cache"

**Comment by danielbachhuber** [comment]
@ari-gold Rename in what sense? Where would this be renamed?

**Comment by danielbachhuber** [comment]
@kibra @ari-gold I think the upstream PR is now in good shape. Maybe @greg-1-anderson should do a final code review at some point, predominately to verify I'm only removing the code that's expected to be removed?

**Comment by ari-gold** [comment]
@danielbachhuber Can you also please update for another pass at the admin UI when the Advanced Page Cache plugin is not installed? 
<img width="909" alt="screenshot 2016-11-29 13 04 16" src="https://cloud.githubusercontent.com/assets/7874556/20728834/6268b20a-b634-11e6-8a66-221128a443de.png">



**Copy**

Want to automatically clear related pages when you update content? Install  [https://github.com/pantheon-systems/pantheon-advanced-page-cache](Pantheon Advanced Page Cache).

Clear Site Cache

Use with care. Clearing the entire site cache will negatively impact performance for a short period of time.

Default Time to Live (TTL)

Maximum time a cached page will be served. A higher TTL typically improves site performance.

**Comment by danielbachhuber** [comment]
@ari-gold Yep, done

**Comment by ari-gold** [comment]
@danielbachhuber thx. pls update install link to <example.com>/wp-admin/plugin-install.php?tab=plugin-information&plugin=pantheon-advanced-page-cache

**Comment by danielbachhuber** [comment]
@ari-gold Added this experience in dae737c

![image](https://cloud.githubusercontent.com/assets/36432/20834489/8b2c814a-b84a-11e6-8cbf-9b69046a5656.png)

**Comment by danielbachhuber** [comment]
@ari-gold Actually, slight change of approach because the installation UX isn't self-contained in the thickbox. Opening the thickbox leads to a UX deadend.

Instead, the link goes to Plugin Install -> Search "Pantheon Advanced Page Cache", and I use a little bit of JS to open the thickbox modal. f8960c3

![image](https://cloud.githubusercontent.com/assets/36432/20835388/2e2508dc-b84f-11e6-9dbb-3bdb0adf1c81.png)

http://dev-pantheon-advanced-page-cache.pantheonsite.io/ has been updated for you to review.
