### ISSUE TITLE
Remove core update nag in the WP Dashboard

### ISSUE THREAD

**Issue by jakebellacera** [pantheon-systems/WordPress#89]
Wordpress 4.7 is out, and we're currently being nagged to update. We currently pull core updates from Pantheon's upstream (this repo, specifically), and the upstream has not been updated to 4.7 yet.

According to [this article in the documentation](https://pantheon.io/docs/upstream-updates/), we should not apply updates from the WP dashboard:

> Do not update core using the WordPress Dashboard, Drush, or WP-CLI; you will overwrite your core.

While we can avoid clicking on the nag to prevent the auto-update, we feel that the Pantheon version of WP should just hide the nag altogether to prevent our core from updating and diverging from Pantheon's upstream. We've done this locally, but I don't see why this couldn't be applied to every site.

Thoughts?

**Comment by jhabdas** [comment]
@jakebellacera updates on this? or can it be closed.

**Comment by jakebellacera** [comment]
FYI - looks like #126 resolved this.
