### ISSUE TITLE
wp-settings.php Line 91: Parse error: syntax error, unexpected '}'

### ISSUE THREAD

**Issue by fourg6x** [pantheon-systems/WordPress#96]
wp-settings.php Line 91: Parse error: syntax error, unexpected '}'

After applying WordPress 4.7-p2 [Security PATCH release].

**Comment by greg-1-anderson** [comment]
@fourg6x wp-settings.php is not altered in that release. Perhaps something else is going on with your site?

Try opening a support ticket.

**Comment by fourg6x** [comment]
Weird, don't mind me then. I just downloaded the entire Pantheon Wordpress core and have squashed a few bugs with a theme... seems to be good now.
