### ISSUE TITLE
Pantheon Page Cache for Site Networks

### ISSUE THREAD

**Issue by hengkit** [pantheon-systems/WordPress#98]
The MU plugin currently operates at the individual site level in a site network. Ideally, it would operate at a network level with overrides by individual sites.

**Comment by jhabdas** [comment]
@hengkit could you provide some more detail for those of us who are not familiar with the MU plugin?

**Comment by nullvariable** [comment]
I consulted with @hengkit and we're good to close this issue.
cc @greg-1-anderson

**Comment by pwtyler** [comment]
Thanks for the followup, @nullvariable. Closing out.
